### ISSUE TITLE
Activation Character Besides <SPACE>

### ISSUE THREAD

**Issue by seemikeplay** [OzymandiasTheGreat/xpander#2]
AWESOME! Thanks for making this!

Not an issue, more of a feature request:
Any chance of making the activation character a custom one instead of just a SPACE?

Like typing "expandthis;" instead of "expandthis "

Or activating without an activation character at all?
If I type "sshaws" it instantly expands to "ssh user@awsserver"??

Thank you for making this, I have been fighting with Autokey for soooo long.

**Comment by OzymandiasTheGreat** [comment]
Ha, you're welcome! I've found Autokey rather lacking as well.
I am planning on adding custom triggers _eventually_.
This will take a while tho, as I'm preoccupied with other things and while I love xpander it's a low priority project.

**Comment by OzymandiasTheGreat** [comment]
Aaand it's been done. Sorry for the delay.
