### ISSUE TITLE
Split into two parts - daemon & GUI

### ISSUE THREAD

**Issue by dufferzafar** [OzymandiasTheGreat/xpander#4]
Have you thought about splitting the project into two parts? 

A daemon - that offers all the text expansion features and a separate GUI application that allows configuration.

This will help people like me who are okay with just using their editor to write phrase files and don't have to use the UI.

**Comment by dufferzafar** [comment]
This doesn't seem hard to do. The codebase already seems to be split in Python & TypeScript. I just tried running the python file `xpander.py` and it seems to have worked!

**Comment by OzymandiasTheGreat** [comment]
Sorry for the late reply, been dealing with the flu.

Actually, it's pretty hard. While the python code can run independently with limited functionality, the hard part is communicating with the electron process.
It's very simple when the python process runs as child process bound through pipes and quite complex if python code runs as an independent daemon.

I've actually considered doing this, even experimented with a few options, but bottom line is this complicates the code base a lot, existing solutions are outdated and unmaintained, and the only benefit I can think of is slightly reduced memory usage.

As for the memory usage, there may be other ways to reduce it.

**Comment by dufferzafar** [comment]
@OzymandiasTheGreat Take care, man!

I actually found a rust based tool that aims to solve similar problem: https://github.com/federico-terzi/espanso/

So I've been using that.
